### ISSUE TITLE
弹窗

### ISSUE THREAD

**Issue by fengliulin** [ranbest/ChineseCharReplace#1]
![image](https://user-images.githubusercontent.com/44517777/128591942-2d98ecb2-8dd7-4ac7-9fde-858ff258bd83.png)
这个弹窗取消了吧！ 输入一个字符弹出一个，非常的恶心，  并且撤回输入中文标点，你也没有提示按什么键盘， 我还是测试出来的才知道是ctrl+z，。

建议增加选项，取消这个恶心的弹窗吧

**Comment by bestv5** [comment]
取消了，增加了配置。v1.5.0
