### ISSUE TITLE
IntelliJ IDEA 2021.2 (Ultimate Edition) 版本没有生效

### ISSUE THREAD

**Issue by minhy77** [ranbest/ChineseCharReplace#2]
![image](https://user-images.githubusercontent.com/33127615/129579501-88a2d209-1863-4445-848f-890a450d74eb.png)

插件版本 1.5.0 

最新版本的 IntelliJ 中没有生效, 请问是目前还不支持么?

**Comment by bestv5** [comment]
支持的呀。我的就是2021.2，标点符号没有替换么？麻烦给个截图。我这边试一下。
另外，idea.log里也会打印一些日志，可以看看是否触发了。

**Comment by minhy77** [comment]
昨天安装插件后没生效, 今天可以了. 我记得安装插件后重启 IDE 了, 不知道什么原因. 多谢

**Comment by bestv5** [comment]
> 昨天安装插件后没生效, 今天可以了. 我记得安装插件后重启 IDE 了, 不知道什么原因. 多谢

ok，可能是缓存，具体我也不知道。有问题欢迎交流!

**Comment by minhy77** [comment]
今天发现, 生效的是非注释的地方, 注释里还是中文标点符号 (golang 和 sql 的注释中), 能否在注释中也生效?

**Comment by bestv5** [comment]
> 今天发现, 生效的是非注释的地方, 注释里还是中文标点符号 (golang 和 sql 的注释中), 能否在注释中也生效?

我在注释中，主要还是写中文。所以为了方便，我设计的时候，注释区域不会替换。
下一个版本里，我再加个配置，注释区域是否要替换。

**Comment by minhy77** [comment]
注释区中文标点转换很有用, 非常期待这个功能, 谢谢
