### ISSUE TITLE
希望能上架 VS Code

### ISSUE THREAD

**Issue by ArminZheng** [ranbest/ChineseCharReplace#5]
这款插件就是使用原生输入法的救星

**Comment by bestv5** [comment]
说实话，VS Code插件我还没开发过，我尝试一下看看，但不保证能完成。

**Comment by bestv5** [comment]
> 这款插件就是使用原生输入法的救星

不好意思，这段时间比较忙，另外，我也没研究会vs插件的开发。上不了vs插件了，你可以看看我这逻辑自己实现一个
